### ISSUE TITLE
[FEATURE] Apply securedBy to resources, and not always merge with methods

### ISSUE THREAD

**Issue by rickmacgillis** [raml-org/raml-php-parser#68]
**The Problem**
The RAML spec [shows](http://raml.org/spec.html#usage-applying-a-security-scheme-to-an-api) that the securedBy parameter may appear on both methods, and resources. The current setup does not allow for resources to use securedBy. Also, the current setup doesn't allow for security restrictions using secondary servers. Method simply merges all securityScheme data into the current request.

**The Solution**
I've changed the code to allow for backwards compatible new features. You can change whether or not  the parser will merge securedBy data with the method or not. I propose that in version 2.0.0 of PHP RAML Parser that we default to not merging the securedBy data as people can merge it later by calling \Raml\Method::addSecurityScheme() with the $merge parameter set to true. That allows for more extensibility, as you'll need to use array_diff() and the like to remove securityScheme data from the method data.

I've also added the ability to add securedBy data to resources. securitySchemes entries are incompatible with resource merging, so there's no need to add that functionality.

**Comment by alecsammon** [comment]
Hi Rick,

Sorry - bit confused by this pull request. Agreed that the securedBy should be merged onto resources as well as methods. However this in it's self is not a backwards incompatible change. 

I'm still confused by why you wouldn't want the security schemes to ever be merged - the library should take whatever RAML is passed to it, and parse it. I don't believe that there should be flags that change the parsing methods.

Therefor I think the changes on Raml/Resource are good, but unsure why any of the other changes are necessary.

(as a sub note this library uses camelCasing throughout)

**Comment by CozyLife** [comment]
My use case is to accommodate security structures validating with one server, then talking to another for the formal request, or simply talking to the same server twice for authentication. The best example I can give is a multi-legged OAuth request in either version. You grab a temporary token from a server, then you use that token for future requests instead of your main token.

If requests get merged with the OAuth request for a token, then you have to pry the two apart and hope that they don't include any of the same keys.
